database:
  spring:
    profiles:
      include: db
    datasource:
      # mem -> mem mean InMemory DB
      url: jdbc:h2:mem:oauthTest;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      # use quotes to avoid YAML interpreting this as a number
      password:

# registration
spring:
  #OAuth2.0 Key Properties
  config:
    import: secret.yml
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${secret.naver.client-id}
            client-secret: ${secret.naver.client-secret}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: 'nickname'
            client-name: Naver
        #provider
        #해당 Provider에 대한 정보는 Naver OAtuh2.0 에 대한 API URL
        provider:
          naver:
            authorization-uri: 'https://nid.naver.com/oauth2.0/authorize'
            token-uri: 'https://nid.naver.com/oauth2.0/token'
            user-info-uri: 'https://openapi.naver.com/v1/nid/me'
            user-name-attribute: response

